const SET_API = 'SET_API';
const SET_PAGE = 'SET_PAGE';
const SET_RESULTS = 'SET_RESULTS';
const SET_ID = 'SET_ID';
const SET_COUNTER = 'SET_COUNTER';

export { SET_API, SET_PAGE, SET_RESULTS, SET_ID, SET_COUNTER };
